#!/bin/bash
while read oldrev newrev ref
do
    if [[ $ref =~ .*/master$ ]];
    then
        echo "Master ref received.  Deploying master branch to production..."
        git --work-tree=/var/www/html/ --git-dir=/root/website/ checkout -f
    else
        echo "Ref $ref successfully received.  Doing nothing: only the master"
    fi
done
